name: ChromaWars
version: 1.0.0
main: cz.xoam24.chromawars.ChromaWars
api-version: '1.21'
description: Splatoon-style Turf Wars minigame
authors: [ xoam24 ]

softdepend:
  - PlaceholderAPI

commands:
  elo:
    description: Správa ELO hráčů
    usage: /elo <add|set|remove|reset> <hráč> <hodnota>
    permission: chromawars.admin
  chroma:
    description: ChromaWars administrace
    usage: /chroma <setlobby|arena|reload>
    permission: chromawars.admin
  join:
    description: Otevře GUI pro výběr týmu
    usage: /join
    permission: chromawars.play
  votemap:
    description: Otevře GUI pro hlasování o mapě
    usage: /votemap
    permission: chromawars.play

permissions:
  chromawars.admin:
    description: Přístup ke všem admin příkazům
    default: op
  chromawars.play:
    description: Povolení hrát ChromaWars
    default: true